core/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'roles', RolUsuarioViewSet)
router.register(r'regiones', RegionViewSet)
router.register(r'comunas', ComunaViewSet)
router.register(r'usuarios', UsuarioCustomViewSet)
router.register(r'talleres', TallerViewSet)
router.register(r'marcas', MarcaViewSet)
router.register(r'tipos-vehiculo', TipoVehiculoViewSet)
router.register(r'vehiculos', VehiculoViewSet)
router.register(r'tipos-agenda', TipoAgendaViewSet)
router.register(r'agendas', AgendaViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    
    path('', index, name="index"),
    path('agendar_hora/', agendar_hora, name="agendar_hora"),
    path('agendar/', agendar, name="agendar"),
    path('contactanos/', contactanos, name="contactanos"),
    path('login/', login, name="login"),
    path('mapa/', mapa, name="mapa"),
    path('mis_reservas/', mis_reservas, name="mis_reservas"),
    path('mis_vehiculos/', mis_vehiculos, name="mis_vehiculos"),
    path('realizar_ticket/', realizar_ticket, name="realizar_ticket"),
    path('solicitar_taller/', solicitar_taller, name="solicitar_taller"),
    path('register_vehiculo/', register_vehiculo, name="register_vehiculo"),
    path('register/', register, name="register"),
    path('sobre_nosotros/', sobre_nosotros, name="sobre_nosotros"),
    path('talleres/', talleres, name="talleres"),
    path('tickets/', tickets, name="tickets"),
    #PANEL DE ADMINISTRACIÓN
    path('administracion/', administracion, name="administracion"),
    
    #ADMINISTRAR TALLERES (CRUD):
    path('administrar_talleres/', administrar_talleres, name="administrar_talleres"),
    path('crear_taller/', crear_taller, name="crear_taller"),
    path('modificar_taller/<int:id_taller>/', modificar_taller, name="modificar_taller"),
    path('eliminar_taller/<int:id_taller>/', eliminar_taller, name='eliminar_taller'),

    # testeo
    path('test/', get_coordinates, name="test"),
    path('autocomplete_address/', autocomplete_address, name='autocomplete_address'),

    #Agendar
    path('agendar_hora/<int:id_taller>/', agendar_hora, name='agendar_hora'),
    path('get_available_hours/', get_available_hours, name='get_available_hours'),

    path('annadir_vehiculo/', annadir_vehiculo, name="annadir_vehiculo"),
    path('modificar_vehiculo/<int:vehiculo_id>/', modificar_vehiculo, name='modificar_vehiculo'),
    path('eliminar_vehiculo/<int:vehiculo_id>/', eliminar_vehiculo, name="eliminar_vehiculo"),

    path('administrar_usuarios', administrar_usuarios, name="administrar_usuarios"),
    path('modificar_usuario/<int:id>/', modificar_usuario, name='modificar_usuario'),
    path('eliminar_usuario/<int:id>/', eliminar_usuario, name='eliminar_usuario'),
    path('crear_usuario/', crear_usuario, name='crear_usuario'),

    path('administrar_mi_taller/', administrar_mi_taller, name="administrar_mi_taller"),
    path('reservas_taller/<int:idTaller>/', reservas_taller, name='reservas_taller'),

    path('perfil_usuario/', perfil_usuario, name='perfil_usuario'),

    path('reporte_pago/<int:idReserva>/', generar_reporte_pago, name='reporte_pago'),

    path('detalle_reserva/<int:id_agenda>/', detalle_reserva, name='detalle_reserva'),

    path('actualizar_estado_agenda/<int:id_agenda>/', actualizar_estado_agenda, name='actualizar_estado_agenda'),
    path('generar_documento_word/<int:id_agenda>/', generar_documento_word, name='generar_documento_word'),

    path('mis_tickets/', mis_tickets, name="mis_tickets"),

    path('crear_ticket/', crear_ticket, name="crear_ticket"),
    path('aceptar_ticket/<int:idTicket>/', aceptar_ticket, name="aceptar_ticket"),
    path('rechazar_ticket<int:idTicket>/', rechazar_ticket, name="rechazar_ticket"),

    path('mensajes/', mensajes, name='mensajes'),
    path('eliminar_mensaje/<int:id_mensaje>/', eliminar_mensaje, name='eliminar_mensaje'),
]

fixspot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

#MODELOS RELACIONADOS AL USUARIO:
class rolUsuario(models.Model):
    idRol = models.AutoField(primary_key=True)
    nombreRol = models.CharField(max_length=20, blank=False, null=False)

    def __str__(self):
        return self.nombreRol

    class Meta:
        permissions = (
            ("cliente_permiso", "Permiso para Cliente"),
            ("encargado_taller_permiso", "Permiso para Encargado de Taller"),
            ("administrador_permiso", "Permiso para Administrador"),
        )
    

class Region(models.Model):
    idRegion = models.AutoField(primary_key=True)
    nombreRegion = models.CharField(max_length=80, blank=False, null=False)

    def __str__(self):
        return self.nombreRegion

class Comuna(models.Model):
    idComuna = models.AutoField(primary_key=True)
    nombreComuna = models.CharField(max_length=80, blank=False, null=False)
    idRegion = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreComuna

class UsuarioCustom(AbstractUser):
    run = models.CharField(max_length=12, blank=False, null=False)
    correo = models.EmailField(blank=False, null=False)
    telefono = models.CharField(max_length=15, blank=False, null=False)
    pnombre = models.CharField(max_length=20, blank=False, null=False)
    ap_paterno = models.CharField(max_length=24, blank=False, null=False)
    direccion = models.CharField(blank=False, null=False, max_length=100)
    idRol = models.ForeignKey(rolUsuario, on_delete=models.CASCADE, blank=True, null=True)
    idComuna = models.ForeignKey(Comuna, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.username
    
class Taller(models.Model):
    idTaller = models.AutoField(primary_key=True)
    nombreTaller = models.CharField(max_length=46, blank=False, null=False)
    descripcion = models.TextField(blank=True, null=True)
    direccion = models.CharField(max_length=100, blank=False, null=False)
    telefono = models.CharField(max_length=15, blank=False, null=False)
    imagen = models.ImageField(upload_to='taller_imagenes/', blank=False, null=False)
    idUsuario = models.ForeignKey('UsuarioCustom', on_delete=models.CASCADE, blank=True, null=True)
    idComuna = models.ForeignKey('Comuna', on_delete=models.CASCADE, blank=True, null=True)
    latitud = models.FloatField(blank=True, null=True)
    longitud = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.nombreTaller

#MODELOS RELACIONADOS AL VEHÍCULO:
class Marca(models.Model):
    idMarca = models.AutoField(primary_key=True)
    nombreMarca = models.CharField(max_length=32, blank=False, null=False)

    def __str__(self):
        return self.nombreMarca

class TipoVehiculo(models.Model):
    idTipo= models.AutoField(primary_key=True)
    nombreTipo = models.CharField(max_length=32, blank=False, null=False)

    def __str__(self):
        return self.nombreTipo

class Vehiculo(models.Model):
    idVehiculo = models.AutoField(primary_key=True)
    patente = models.CharField(blank=False, null=False, max_length=6)
    modelo = models.CharField(blank=False, null=False, max_length=20)
    subModelo = models.CharField(blank=True, null=True, max_length=20)
    anno = models.IntegerField(blank=False, null=False)
    idUsuario = models.ForeignKey(UsuarioCustom, on_delete=models.CASCADE, blank=True, null=True)
    idMarca = models.ForeignKey(Marca, on_delete=models.CASCADE, blank=False, null=False)
    idTipoVehiculo = models.ForeignKey(TipoVehiculo, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return self.patente

#MODELOS RELACIONADOS A LA AGENDA:
class TipoAgenda(models.Model):
    idTipo= models.AutoField(primary_key=True)
    nombreTipo = models.CharField(max_length=32, blank=False, null=False)

    def __str__(self):
        return self.nombreTipo
    
class EstadoAgenda(models.Model):
    idEstado = models.AutoField(primary_key=True)
    nombreEstado = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nombreEstado

class Agenda(models.Model):
    idAgenda = models.AutoField(primary_key=True)
    fechaAtencion = models.DateField(null=False, blank=False)
    horaAtencion = models.TimeField(blank=False, null=False)
    idTipoAgenda = models.ForeignKey(TipoAgenda, on_delete=models.CASCADE, blank=False, null=False)
    idTaller = models.ForeignKey(Taller, on_delete=models.CASCADE, blank=False, null=False) 
    idVehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE, blank=False, null=False)
    cliente = models.ForeignKey(UsuarioCustom, on_delete=models.CASCADE, blank=False, null=False)
    estado = models.ForeignKey(EstadoAgenda, on_delete=models.CASCADE, blank=True, null=True, default=1) 

    def __str__(self):
        return self.idAgenda

    
class ReportePago(models.Model):
    idReporte = models.AutoField(primary_key=True)
    reserva = models.OneToOneField(Agenda, on_delete=models.CASCADE)
    comentario = models.TextField(blank=True, null=True)
    monto = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Reporte de pago para reserva {self.reserva.idAgenda}"
    
#Modelos relacionados a los tickets
class EstadoTicket(models.Model):
    idEstado = models.AutoField(primary_key=True)
    NombreEstado = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.NombreEstado
    
class Ticket(models.Model):
    idTicket = models.AutoField(primary_key=True)
    asunto = models.TextField(blank=False, null=False)
    solicitante = models.ForeignKey(UsuarioCustom, on_delete=models.CASCADE, blank=False, null=False)
    EstadoTicket = models.ForeignKey(EstadoTicket, on_delete=models.CASCADE, blank=False, null=False)
    
class Contacto(models.Model):
    idContacto = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, blank=False, null=False)
    correo = models.EmailField(blank=False, null=False)
    telefono = models.CharField(max_length=15, blank=False, null=False)
    asunto = models.TextField(blank=False, null=False)

core/templates/core/administracion.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
<!-- INICIO ENCABEZADO -->
<div class="">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5 mt-5">
                <div class="intro-excerpt">
                    <h1 class="fw-bold text-center">PANEL DE ADMINISTRACIÓN DE FIXSPOT</h1>
                </div>
            </div>
        </div>
    </div>
    <br><br><br>
</div>
<!-- FIN ENCABEZADO -->

<!-- Inicio panel de administración -->
<div class="bg-page">
    <br><br><br><br>
    <div class="container mx-auto align-items-center">
        <div class="row justify-content-center">
            <!-- Card 1 -->
            <div class="col-md-3 accordion mb-4 d-flex">
                <div class="card mb-4 shadow-lg rounded-5 flex-fill">
                    <div class="card-body text-center bg-dark rounded-5 d-flex flex-column">
                        <i class="fas fa-users fa-3x mb-3 text-white"></i>
                        <h5 class="card-title text-white">Gestión de Usuarios</h5>
                        <p class="text-white flex-grow-1">Administrar usuarios y sus roles.</p>
                        <a href="{% url 'administrar_usuarios' %}" class="btn btn-primary mt-auto">Ir</a>
                    </div>
                </div>
            </div>
            <!-- Card 2 -->
            <div class="col-md-3 mb-4 d-flex">
                <div class="card mb-4 shadow-lg rounded-5 flex-fill">
                    <div class="card-body text-center bg-dark rounded-5 d-flex flex-column">
                        <i class="fa-solid fa-wrench fa-3x mb-3 text-white"></i>
                        <h5 class="card-title text-white">Gestión de talleres</h5>
                        <p class="text-white flex-grow-1">Ver, crear, modificar y eliminar talleres.</p>
                        <a href="{% url 'administrar_talleres' %}" class="btn btn-primary mt-auto">Ir</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 mb-4 d-flex">
                <div class="card mb-4 shadow-lg rounded-5 flex-fill">
                    <div class="card-body text-center bg-dark rounded-5 d-flex flex-column">
                        <i class="fa-solid fa-ticket fa-3x mb-3 text-white"></i>
                        <h5 class="card-title text-white">Gestión de Tickets</h5>
                        <p class="text-white flex-grow-1">Ver tickets, y responder a ellos.</p>
                        <a href="{% url 'tickets' %}" class="btn btn-primary mt-auto">Ir</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 mb-4 d-flex">
                <div class="card mb-4 shadow-lg rounded-5 flex-fill">
                    <div class="card-body text-center bg-dark rounded-5 d-flex flex-column">
                        <i class="fa-solid fa-message fa-3x mb-3 text-white"></i>
                        <h5 class="card-title text-white">Mensajes</h5>
                        <p class="text-white flex-grow-1">Ver mensajes de contacto con la página.</p>
                        <a href="{% url 'mensajes' %}" class="btn btn-primary mt-auto">Ir</a>
                    </div>
                </div>
            </div>
        </div>
    </div> 
    <br><br><br><br><br><br>
</div>

{% endblock contenido %}
{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock js %}

core/templates/core/administrar_mi_taller.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
<!-- INICIO ENCABEZADO -->
<div class="">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5 mt-5">
                <div class="intro-excerpt">
                    <h1 class="fw-bold text-center text-uppercase">PANEL DE ADMINISTRACIÓN TALLER</h1>
                </div>
            </div>
        </div>
    </div>
    <br><br><br>
</div>
<!-- FIN ENCABEZADO -->

<!-- Inicio panel de administración -->
<div class="bg-page">
    <br><br><br><br>
    {% if taller %}
    <h1 class="text-center fw-bold text-uppercase">TALLER: {{ taller.nombreTaller }}</h1>
    <div class="container mx-auto align-items-center">
        <div class="row justify-content-center">
            <!-- Card 1 -->
            <div class="col-md-4 mt-3 mb-4 d-flex">
                <div class="card mb-4 shadow-lg rounded-5 flex-fill">
                    <div class="card-body text-center bg-dark rounded-5 d-flex flex-column">
                        <i class="fa-solid fa-book fa-3x mb-3 text-white"></i>
                        <h5 class="card-title text-white">RESERVAS</h5>
                        <p class="text-white flex-grow-1">Administrar reservas en el taller.</p>
                        <a href="{% url 'reservas_taller' taller.idTaller %}" class="btn btn-primary mt-auto">Ir</a>
                    </div>
                </div>
            </div>
            <!-- Card 2 -->
            <div class="col-md-4 mb-4 d-flex">
                <div class="card mb-4 shadow-lg rounded-5 flex-fill">
                    <div class="card-body text-center bg-dark rounded-5 d-flex flex-column">
                        <i class="fa-solid fa-ticket fa-3x mb-3 text-white"></i>
                        <h5 class="card-title text-white">REALIZAR TICKET</h5>
                        <p class="text-white flex-grow-1">Hacer solicitudes al administrador para ajustes en el taller.</p>
                        <a href="{% url 'mis_tickets' %}" class="btn btn-primary mt-auto">Ir</a>
                    </div>
                </div>
            </div>
        </div>
    </div> 
    <br><br><br><br><br><br>
    {% endif %}
</div>



{% endblock contenido %}

core/templates/core/agendar_hora.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}
<div class="">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 mt-5">
                <div class="intro-excerpt">
                    <h1 class="fw-bold text-center">AGENDAR</h1>
                </div>
            </div>
        </div>
    </div>
    <br><br><br>
</div>

<div class="bg-white">
  <br><br><br>
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center mt-4 mb-5">
          <div class="col-md-8">
            <h1 class="text-center text-uppercase fw-bold">Agendar Hora en {{ taller.nombreTaller }}</h1>
            <form method="POST" id="agendar-form" class="p-4 rounded shadow-lg">
              {% csrf_token %}
              <div class="form-group">
                {{ form | crispy }}
              </div>
              <input type="submit" class="btn rounded-pill btn-background btn-lg mt-5 d-flex text-center mx-auto" value="Agendar hora" onclick="return confirmacionAgendar()">
            </form>
          </div>
        </div>
        <br><br>
    </div>
    <style>
        .form-control {
          height: 50px;
          border-radius: 20px;
        }
    </style>
</div>

{% endblock contenido %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    function confirmacionAgendar() {
        Swal.fire({
            title: '¿Está seguro de agendar una hora con el taller?',
            text: 'Esta acción no se puede deshacer.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sí, Agendar',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById('agendar-form').submit();
            }
        });
        return false;
    }

    $(document).ready(function() {
        $('#id_fechaAtencion').change(function() {
            var selectedDate = $(this).val();
            var idTaller = "{{ taller.idTaller }}";

            $.ajax({
                url: "{% url 'get_available_hours' %}",
                data: {
                    'date': selectedDate,
                    'id_taller': idTaller
                },
                success: function(data) {
                    var $horaAtencion = $('#id_horaAtencion');
                    $horaAtencion.empty();
                    $.each(data.available_hours, function(index, value) {
                        $horaAtencion.append('<option value="' + value + '">' + value + '</option>');
                    });
                }
            });
        });
    });
</script>
{% endblock js %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FixSpot</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <link rel="icon" href="{% static 'core/img/favicon.ico' %}" type="image/x-icon">

    {% block css %}
    {% endblock %}
</head>
<body>

    <!-- INICIO DEL NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-5 mb-5 mt-3" style="margin-left: 50px; margin-right: 50px;">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                <a class="navbar-brand d-lg-none" href="#">
                    <img src="{% static 'core/img/fixspot-logo-sinfondo.png' %}" alt="Logo" class="img-fluid" style="max-height: 60px;">
                </a>
                
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-white fw-bold" href="{% url 'talleres' %}">Talleres</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white fw-bold " href="{% url 'mapa' %}#">Mapa</a>
                    </li>
                </ul>
                
                <div class="container d-flex">
                    <a class="navbar-brand d-none d-lg-block mx-auto" href="{% url 'index' %}">
                        <img src="{% static 'core/img/fixspot-logo-sinfondo.png' %}" alt="Logo" class="img-fluid" style="max-height: 100px;">
                    </a>
                </div>
            
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-white fw-bold" href="{% url 'contactanos' %}">Contacto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white fw-bold" href="{% url 'sobre_nosotros' %}" style="white-space: nowrap;">Sobre nosotros</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link text-white dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end custom-dropdown text-center bg-dark" aria-labelledby="userDropdown">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item custom-dropdown-item fw-bold text-uppercase" href="{% url 'perfil_usuario' %}"><i class="fa-solid fa-user"></i> {{ user.pnombre }} {{ user.ap_paterno }} </a></li>
                                {% if user.idRol_id == 3 %}
                                    <li><a class="dropdown-item custom-dropdown-item fw-bold" href="{% url 'administracion' %}"><i class="fa-solid fa-lock"></i> ADMINISTRACIÓN </a></li>
                                {% endif %}
                                <li><a class="dropdown-item custom-dropdown-item fw-bold" href="{% url 'mis_vehiculos' %}"><i class="fa-solid fa-car"></i> MIS VEHÍCULOS </a></li>
                                <li><a class="dropdown-item custom-dropdown-item fw-bold" href="{% url 'mis_reservas' %}"><i class="fa-solid fa-book"></i> MIS RESERVAS </a></li>
                                {% if user.idRol_id == 2 %}
                                    <li><a class="dropdown-item custom-dropdown-item fw-bold" href="{% url 'administrar_mi_taller' %}"><i class="fa-solid fa-gear"></i> MI TALLER </a></li>
                                {% endif %}
                                <li>
                                    <form method="POST" action="{% url 'logout' %}">
                                        {% csrf_token %}
                                        <button class="dropdown-item custom-dropdown-item fw-bold" type="submit"><i class="fa-solid fa-right-from-bracket"></i> CERRAR SESIÓN </button>
                                    </form>
                                </li>
                            {% else %}
                                <li><a class="dropdown-item custom-dropdown-item fw-bold" href="{% url 'login' %}"><i class="fa-solid fa-right-to-bracket"></i> INICIAR SESIÓN </a></li>
                                <li><a class="dropdown-item custom-dropdown-item fw-bold" href="{% url 'register' %}"><i class="fa-solid fa-cash-register"></i> REGISTRARSE </a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block contenido %}
    {% endblock %}
    <div class="bg-page">
        <footer class="navbar navbar-expand-lg bg-dark rounded-5 mb-5 mt-3 footer" style="margin-left: 15px; margin-right: 15px;">
            <div class="container d-flex flex-column flex-lg-row justify-content-center justify-content-lg-between align-items-center">
                <div class="footer-logo text-center mb-3 mb-lg-0">
                    <a href="{% url 'index' %}">
                        <img src="{% static 'core/img/fixspot-logo-sinfondo.png' %}" alt="Logo" class="img-fluid w-50 h-50">
                    </a>
                </div>
                <div class="footer-links text-center mb-3 mb-lg-0">
                    <ul class="list-unstyled d-flex mb-0">
                        <li class="mx-3"><a href="{% url 'talleres' %}" class="text-white text-decoration-none fw-bold">Talleres</a></li>
                        <li class="mx-3"><a href="{% url 'mapa' %}" class="text-white text-decoration-none fw-bold">Mapa</a></li>
                        <li class="mx-3"><a href="{% url 'contactanos' %}" class="text-white text-decoration-none fw-bold">Contacto</a></li>
                        <li class="mx-3"><a href="{% url 'sobre_nosotros' %}" class="text-white text-decoration-none fw-bold">Sobre nosotros</a></li>
                    </ul>
                </div>
                <div class="footer-tagline text-center text-lg-end">
                    <h1 class="mx-3"><a href="#" class="text-white text-decoration-none fw-bold h3">Talleres mecánicos a tu alcance</a></h1>
                </div>
            </div>
        </footer>
    </div>
    
    {% block js %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    {% endblock %}
</body>
</html>